-- Step 1: Enable the pgvector extension for semantic similarity search
CREATE EXTENSION IF NOT EXISTS vector;

-- Step 1: Create the 'submissions' table for raw citizen submissions
CREATE TABLE IF NOT EXISTS submissions (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    timestamp TIMESTAMPTZ DEFAULT now() NOT NULL,
    channel TEXT DEFAULT 'web' NOT NULL,
    raw_text TEXT,
    audio_url TEXT,
    photo_url TEXT,
    language TEXT NOT NULL,
    geo JSONB,
    citizen_id_hash TEXT NOT NULL
);

-- Add comments for 'submissions' mapping to roadmap schema
COMMENT ON TABLE submissions IS 'Stores raw citizen submissions containing text, voice (audio_url), or photo (photo_url) inputs.';
COMMENT ON COLUMN submissions.id IS 'Unique identifier for the submission';
COMMENT ON COLUMN submissions.timestamp IS 'Time when the submission was made';
COMMENT ON COLUMN submissions.channel IS 'Intake channel (e.g. web, whatsapp)';
COMMENT ON COLUMN submissions.raw_text IS 'Original user-provided text, if any';
COMMENT ON COLUMN submissions.audio_url IS 'URL of recorded audio/voice note, if any';
COMMENT ON COLUMN submissions.photo_url IS 'URL of uploaded photo, if any';
COMMENT ON COLUMN submissions.language IS 'Detected language of submission';
COMMENT ON COLUMN submissions.geo IS 'Geographic coordinates or administrative ward information (JSON format)';
COMMENT ON COLUMN submissions.citizen_id_hash IS 'Hashed identifier for the citizen to preserve anonymity';

-- Step 1: Create the 'enriched_submissions' table for AI enrichment results
CREATE TABLE IF NOT EXISTS enriched_submissions (
    id UUID PRIMARY KEY REFERENCES submissions(id) ON DELETE CASCADE,
    normalized_text_en TEXT NOT NULL,
    category TEXT NOT NULL,
    need_type TEXT NOT NULL,
    urgency TEXT NOT NULL,
    sentiment TEXT NOT NULL,
    canonical_location TEXT,
    extracted_entities JSONB DEFAULT '{}'::jsonb NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Add comments for 'enriched_submissions' mapping to roadmap schema
COMMENT ON TABLE enriched_submissions IS 'Stores AI-enriched submission metadata generated by the enrichment pipeline.';
COMMENT ON COLUMN enriched_submissions.id IS 'Foreign key referencing the raw submission';
COMMENT ON COLUMN enriched_submissions.normalized_text_en IS 'Normalized and translated English version of the raw submission';
COMMENT ON COLUMN enriched_submissions.category IS 'Inferred category (e.g. waste management, water, sanitation)';
COMMENT ON COLUMN enriched_submissions.need_type IS 'Specific issue classification';
COMMENT ON COLUMN enriched_submissions.urgency IS 'Calculated urgency level (low, medium, high)';
COMMENT ON COLUMN enriched_submissions.sentiment IS 'Sentiment analysis of the citizen request';
COMMENT ON COLUMN enriched_submissions.canonical_location IS 'Geographic normalization mapping to recognized locations';
COMMENT ON COLUMN enriched_submissions.extracted_entities IS 'JSON metadata of extracted entities (places, agencies, etc.)';

-- Step 1: Create the 'embeddings' table to store vector embeddings for semantic search
CREATE TABLE IF NOT EXISTS embeddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    submission_id UUID UNIQUE NOT NULL REFERENCES submissions(id) ON DELETE CASCADE,
    vector vector(768) NOT NULL, -- Vertex AI text-embeddings defaults to 768 dimensions
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Add comments for 'embeddings' mapping to roadmap schema
COMMENT ON TABLE embeddings IS 'Stores high-dimensional vector embeddings generated on the English normalized text.';
COMMENT ON COLUMN embeddings.submission_id IS 'References the submission associated with this embedding';
COMMENT ON COLUMN embeddings.vector IS '768-dimensional float vector representation';

-- Create an index for pgvector cosine distance search
-- In real workloads with >1000 items, choose HNSW:
-- CREATE INDEX ON embeddings USING hnsw (vector vector_cosine_ops);

-- Step 1: Create the 'priorities' table for final ranked recommendations
CREATE TABLE IF NOT EXISTS priorities (
    work_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title TEXT NOT NULL,
    category TEXT NOT NULL,
    demand_score NUMERIC DEFAULT 0.0 NOT NULL,
    demand_count INTEGER DEFAULT 0 NOT NULL,
    hotspot_geo JSONB DEFAULT '{}'::jsonb NOT NULL,
    supporting_evidence JSONB DEFAULT '[]'::jsonb NOT NULL,
    rank INTEGER,
    explanation TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT now() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT now() NOT NULL
);

-- Add comments for 'priorities' mapping to roadmap schema
COMMENT ON TABLE priorities IS 'Stores ranked priority items synthesized by the data fusion and scoring algorithm.';
COMMENT ON COLUMN priorities.work_id IS 'Unique identifier for the priority work project';
COMMENT ON COLUMN priorities.title IS 'Short, descriptive title of the priority project';
COMMENT ON COLUMN priorities.category IS 'Primary category of the project';
COMMENT ON COLUMN priorities.demand_score IS 'Weighted rank score based on volume, urgency, and public data';
COMMENT ON COLUMN priorities.demand_count IS 'Raw count of citizen submissions supporting this priority';
COMMENT ON COLUMN priorities.hotspot_geo IS 'Aggregated Mapbox-compatible geo data: {lat, lng, density}';
COMMENT ON COLUMN priorities.supporting_evidence IS 'JSON array containing key evidence, quotes, and referencing submission IDs';
COMMENT ON COLUMN priorities.rank IS 'Rank placement of this item (1 = highest priority)';
COMMENT ON COLUMN priorities.explanation IS 'Detailed explanation of why this priority is ranked and the rationale';

-- Step 3: Write the Postgres function (RPC) for similarity matching
CREATE OR REPLACE FUNCTION match_submissions (
    query_embedding vector(768),
    match_threshold float,
    match_count int
)
RETURNS TABLE (
    submission_id uuid,
    similarity float
)
LANGUAGE plpgsql
AS $$
BEGIN
    RETURN QUERY
    SELECT
        embeddings.submission_id,
        (1 - (embeddings.vector <=> query_embedding))::float AS similarity
    FROM embeddings
    WHERE (1 - (embeddings.vector <=> query_embedding)) > match_threshold
    ORDER BY embeddings.vector <=> query_embedding ASC
    LIMIT match_count;
END;
$$;

COMMENT ON FUNCTION match_submissions IS 'Performs a pgvector top-k similarity search based on cosine distance.';
